name: Build NPM package from sources

on:

  workflow_dispatch:
    inputs:
      ignore-cache:
        required: false
        type: boolean
        description: build without cache

  workflow_call:
    inputs:
      ignore-cache:
        required: false
        type: boolean
        description: build without node_modules cache

jobs:
  build:
    permissions:
      actions: read
      contents: read
    uses: IT-Service-NPM/.github/.github/workflows/build-npm-package.yml@main
    with:
      ignore-cache: ${{ inputs.ignore-cache }}
    secrets: inherit
